# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d359955e3050b7f465a5b006e0baebeff1c48a4635fcaf93990d5e164354117e1c91ff95ee1211e923f7a63eabd7ae9fbc8b9d71be7e5d8e12ad04c758a9c26

test:
  secret_key_base: e91bd2ca986982b8b5ac72a01f765e9cffdcdd4f0355433a710a689a8b35ee992c7ca74a3c846acb88985403e2917f0c6af561e96d420c0e911efb4c806531a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
